name: widget-server pipe DockerHub
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Login to DockerHub
        id: login-dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tag
        id: generate-tags
        run: |
         SHA=$(echo $GITHUB_SHA | head -c7)
         echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_REPOSITORY }}:${{ steps.generate-tags.outputs.sha }}
        
      # - name: Build and push Docker image to dockerhub
      #   env:
      #     DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
      #     IMAGE_TAG: ${{ steps.generate-tags.outputs.sha }}
      #   id: build-and-push-image
      #   run: |
      #     docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
      #     docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG

      